---
- name: Get Pods Status
  hosts: all
  gather_facts: true
  tasks:
    - name: run oc get pods
      cmd: oc get pods -n {{ namespace }}
      register: result
    - name: show result
      debug:
        msg: "{{ result.stdout }}"
