---
 - hosts: all
   tasks:
   - name: Create local MicroShift-Fast Datapath repository directory
     ansible.builtin.file:
       path: "{{ microshift_local }}"
       state: directory
       mode: '0755'
     become: true
       
   - name: Syncronize the local MicroShift repository
     #shell: reposync --arch=$(uname -i) --arch=noarch --gpgcheck --download-path "{{ microshift_local }}" --repo=rhocp-4.12-for-rhel-8-x86_64-rpms --repo=fast-datapath-for-rhel-8-x86_64-rpms
     shell: curl "http://192.168.0.29/repos/fast-datapath.tgz" -o "{{ microshift_local }}/fast-datapath.tgz";tar -xzf "{{ microshift_local }}"/fast-datapath.tgz -C "{{ microshift_local }}";rm -r -f "{{ microshift_local }}"/fast-datapath.tgz;curl "http://192.168.0.29/repos/rhocp.tgz" -o "{{ microshift_local }}/rhocp.tgz";tar -xzf "{{ microshift_local }}"/rhocp.tgz -C "{{ microshift_local }}";rm -r -f "{{ microshift_local }}"/rhocp.tgz
     become: true
     
   - name: Remove CoreOS packages in repository
     shell: find "{{ microshift_local }}" -name \*coreos\* -print -exec rm -f {} \;
     become: true
     
   - name: Create repository 
     shell: createrepo "{{ microshift_local }}"
     become: true
     
   - name: Creating repository Toml file
     copy:
       dest: "{{ microshift_local }}/microshift.toml"
       content: |
         id = "microshift-local"
         name = "MicroShift local repo"
         type = "yum-baseurl"
         url = "file://{{ microshift_local }}"
         check_gpg = false
         check_ssl = false
         system = false
     become: true
         
   - name: Add local-repository to composer sources
     shell: composer-cli sources add "{{ microshift_local }}"/microshift.toml
     become: true
